"""Checks the 1974/75 data and results against independent historical records."""

from datetime import date
from pathlib import Path

import pytest

from standings.csv_io import read_results
from standings.table import compute_table

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEEK10_RESULTS = PROJECT_ROOT / "data" / "results_1974-75_week10.csv"
FULL_SEASON_RESULTS = PROJECT_ROOT / "tests" / "fixtures" / "results_1974-75_full_season.csv"

CLUBS_1974_75 = {
    "Arsenal", "Birmingham City", "Burnley", "Carlisle United", "Chelsea",
    "Coventry City", "Derby County", "Everton", "Ipswich Town", "Leeds United",
    "Leicester City", "Liverpool", "Luton Town", "Manchester City", "Middlesbrough",
    "Newcastle United", "Queens Park Rangers", "Sheffield United", "Stoke City",
    "Tottenham Hotspur", "West Ham United", "Wolverhampton Wanderers",
}  # fmt: skip

SEASON_START = date(1974, 8, 17)
WEEK10_END = date(1974, 10, 25)

# Final 1974/75 First Division table as published (Wikipedia, "1974-75 Football
# League First Division"). Written out by hand, not generated by this code.
PUBLISHED_FINAL_TABLE = [
    (1, "Derby County", 42, 21, 11, 10, 67, 49, "1.367", 53),
    (2, "Liverpool", 42, 20, 11, 11, 60, 39, "1.538", 51),
    (3, "Ipswich Town", 42, 23, 5, 14, 66, 44, "1.500", 51),
    (4, "Everton", 42, 16, 18, 8, 56, 42, "1.333", 50),
    (5, "Stoke City", 42, 17, 15, 10, 64, 48, "1.333", 49),
    (6, "Sheffield United", 42, 18, 13, 11, 58, 51, "1.137", 49),
    (7, "Middlesbrough", 42, 18, 12, 12, 54, 40, "1.350", 48),
    (8, "Manchester City", 42, 18, 10, 14, 54, 54, "1.000", 46),
    (9, "Leeds United", 42, 16, 13, 13, 57, 49, "1.163", 45),
    (10, "Burnley", 42, 17, 11, 14, 68, 67, "1.015", 45),
    (11, "Queens Park Rangers", 42, 16, 10, 16, 54, 54, "1.000", 42),
    (12, "Wolverhampton Wanderers", 42, 14, 11, 17, 57, 54, "1.056", 39),
    (13, "West Ham United", 42, 13, 13, 16, 58, 59, "0.983", 39),
    (14, "Coventry City", 42, 12, 15, 15, 51, 62, "0.823", 39),
    (15, "Newcastle United", 42, 15, 9, 18, 59, 72, "0.819", 39),
    (16, "Arsenal", 42, 13, 11, 18, 47, 49, "0.959", 37),
    (17, "Birmingham City", 42, 14, 9, 19, 53, 61, "0.869", 37),
    (18, "Leicester City", 42, 12, 12, 18, 46, 60, "0.767", 36),
    (19, "Tottenham Hotspur", 42, 13, 8, 21, 52, 63, "0.825", 34),
    (20, "Luton Town", 42, 11, 11, 20, 47, 65, "0.723", 33),
    (21, "Chelsea", 42, 9, 15, 18, 42, 72, "0.583", 33),
    (22, "Carlisle United", 42, 12, 5, 25, 43, 59, "0.729", 29),
]


def load(path):
    with path.open(newline="", encoding="utf-8") as stream:
        return read_results(stream)


def as_rows(standings):
    return [
        (
            s.position,
            s.record.team,
            s.record.played,
            s.record.won,
            s.record.drawn,
            s.record.lost,
            s.record.goals_for,
            s.record.goals_against,
            f"{float(s.record.goal_average):.3f}",
            s.record.points,
        )
        for s in standings
    ]


# --- Full season: proves data and rules against the published final table --


def test_full_season_has_every_fixture_exactly_once():
    results = load(FULL_SEASON_RESULTS)
    assert len(results) == 22 * 21
    fixtures = {(r.home_team, r.away_team) for r in results}
    assert fixtures == {(h, a) for h in CLUBS_1974_75 for a in CLUBS_1974_75 if h != a}


def test_full_season_final_table_matches_published_table():
    assert as_rows(compute_table(load(FULL_SEASON_RESULTS))) == PUBLISHED_FINAL_TABLE


def test_liverpool_second_on_goal_average_where_goal_difference_would_differ():
    # Liverpool (60-39, +21) and Ipswich (66-44, +22) both finished on 51 points.
    # Goal average puts Liverpool second; goal difference would have put Ipswich second.
    table = {s.record.team: s for s in compute_table(load(FULL_SEASON_RESULTS))}
    liverpool, ipswich = table["Liverpool"], table["Ipswich Town"]
    assert liverpool.record.points == ipswich.record.points == 51
    liverpool_difference = liverpool.record.goals_for - liverpool.record.goals_against
    ipswich_difference = ipswich.record.goals_for - ipswich.record.goals_against
    assert liverpool_difference < ipswich_difference
    assert (liverpool.position, ipswich.position) == (2, 3)


# --- Week 10 input: checks the file we submit is complete and clean -------


@pytest.fixture(scope="module")
def week10():
    return load(WEEK10_RESULTS)


def test_week10_uses_exactly_the_22_clubs(week10):
    teams = {t for r in week10 for t in (r.home_team, r.away_team)}
    assert teams == CLUBS_1974_75


def test_week10_dates_run_from_season_start_to_end_of_week_10(week10):
    dates = [r.date for r in week10]
    assert min(dates) == SEASON_START
    assert max(dates) <= WEEK10_END
    assert date(1974, 10, 19) in dates


def test_week10_has_148_matches_and_no_repeated_fixture(week10):
    assert len(week10) == 148
    fixtures = [(r.home_team, r.away_team) for r in week10]
    assert len(set(fixtures)) == len(fixtures)


def test_week10_is_exactly_the_full_season_up_to_week_10(week10):
    full_season = load(FULL_SEASON_RESULTS)
    assert sorted(week10, key=repr) == sorted(
        (r for r in full_season if r.date <= WEEK10_END), key=repr
    )


def test_week10_matches_published_standings_on_5_october_1974(week10):
    # Top three on 5 October 1974 as published: Ipswich 16, Liverpool 15, Man City 15.
    table = {
        s.record.team: s.record
        for s in compute_table(r for r in week10 if r.date <= date(1974, 10, 5))
    }
    assert (table["Ipswich Town"].won, table["Ipswich Town"].drawn, table["Ipswich Town"].lost) == (8, 0, 3)
    assert (table["Liverpool"].won, table["Liverpool"].drawn, table["Liverpool"].lost) == (7, 1, 3)
    assert (table["Manchester City"].won, table["Manchester City"].drawn, table["Manchester City"].lost) == (6, 3, 2)
